channels:
- conda-forge
dependencies:
- python=3.10.0
- pip<=25.3
- pip:
  - mlflow==2.13.1
  - cloudpickle==3.1.2
  - numpy==1.24.4
  - packaging==24.2
  - psutil==7.1.3
  - pyyaml==6.0.3
  - scikit-learn==1.4.2
  - scipy==1.10.1
name: mlflow-env
